stages:
    - prepare_environment
    - docker_run
    - clone_projects
    - llvm_build
    - seal_build
    - heaan_build
    - HEonGPU_build
    - Hecate_build
    - Hecate_env
    - testing_Hecate_Pass
    - testing_Hecate_Benchmark
    - save_result

# Global variables for centralized path management
variables:
    CI_USER: "gitlab-runner"
    CI_USER_HOME: "/home/gitlab-runner"
    CI_DATA_DIR: "/home/gitlab-runner/data"
    CI_RESULTS_DIR: "/home/gitlab-runner/results"
    CI_INSTALL_DIR: "/home/gitlab-runner/install"
    CI_DOCKER_HOME: "/home/gitlab-runner"

before_script:
    - date

after_script:
    - date

.irregularly_template:
    tags:
        - hestia_runner
    rules:
        - if: "$CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE == 'schedule' && $SCHEDULE_TYPE == 'irregularly'"
          when: always

.weekly_template:
    tags:
        - hestia_runner
    rules:
        - if: "$CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE == 'schedule' && ($SCHEDULE_TYPE == 'weekly' || $SCHEDULE_TYPE == 'irregularly')"
          when: always

Preparing Environment - docker build:
    extends:
        - .irregularly_template
    stage: prepare_environment
    script:
        - echo "Preparing Environment - docker build"
        - cd script
        #- docker build --no-cache -t hecate_ci_docker_image --target cuda12 .
        - docker build -t hecate_ci_docker_image --target cuda12 .
        - |
          if [ "$(docker images -f 'dangling=true' -q)" ]; then
            echo "Removing dangling Docker images..."
            docker rmi $(docker images -f 'dangling=true' -q) || echo "Failed to remove some images, continuing..."
          else
            echo "No dangling Docker images found."
          fi

Preparing Environment - docker execution:
    extends:
        - .irregularly_template
    stage: docker_run
    script:
        - echo "Preparing Environment - docker execution"
        - |
          if [ $(docker ps -aq -f name=hecate_ci_container) ]; then
            echo "Container already exists. Stopping and removing..."
            docker stop hecate_ci_container || true
            docker rm hecate_ci_container || true
          fi
        - >
          docker run -itd --gpus all --name hecate_ci_container
          -e HOST_USERNAME=${CI_USER}
          -e HOST_UID=$(id -u)
          -e HOST_GID=$(id -g)
          -v "$(pwd):${CI_USER_HOME}/hecate-compiler"
          -v "${CI_DATA_DIR}/results:${CI_RESULTS_DIR}"
          -v "${CI_USER_HOME}/.ssh:${CI_DOCKER_HOME}/.ssh"
          hecate_ci_docker_image

Clone projects using shell script:
    extends:
        - .irregularly_template
    stage: clone_projects
    script:
        - echo  "Clone projects using shell script"
        - docker cp ${CI_DATA_DIR}/clone_projects.sh hecate_ci_container:${CI_DOCKER_HOME}/hecate-compiler/script/clone_projects.sh
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/hecate-compiler/script/ && ./clone_projects.sh"
        - echo "Cloning completed!"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME} && mkdir install"

llvm build:
    extends:
        - .irregularly_template
    stage: llvm_build
    script:
        - echo "LLVM build"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/llvm-project && git log -n 1 HEAD"
        #- docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/hecate-compiler/script && ./Build.sh llvm"
        - >
          docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/llvm-project &&
          cmake -GNinja -Bbuild
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_BUILD_TYPE=Release
          -DLLVM_ENABLE_PROJECTS=mlir
          -DLLVM_INSTALL_UTILS=ON
          -DLLVM_TARGETS_TO_BUILD=host
          -DCMAKE_INSTALL_PREFIX=${CI_INSTALL_DIR}/MLIR
          llvm"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/llvm-project && cmake --build build"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/llvm-project && cmake --install build"

SEAL build:
    extends:
        - .irregularly_template
    stage: seal_build
    script:
        - echo "SEAL build"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/SEAL && git log -n 1 HEAD"
        #- docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/hecate-compiler/script && ./Build.sh seal"
        - >
          docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/SEAL &&
          cmake -S . -B build -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_INSTALL_PREFIX=${CI_INSTALL_DIR}/SEAL"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/SEAL && cmake --build build"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/SEAL && cmake --install build"

HEonGPU build:
    extends:
        - .irregularly_template
    stage: HEonGPU_build
    script:
        - echo "HEonGPU build"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/HEonGPU && git log -n 1 HEAD"
        #- docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/hecate-compiler/script && ./Build.sh heon 86"
        - >
          docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/HEonGPU &&
          cmake -S . -D CMAKE_CUDA_ARCHITECTURES=86
          -D CMAKE_INSTALL_PREFIX=${CI_INSTALL_DIR}/HEON
          -D HEonGPU_BUILD_BENCHMARKS=ON
          -D HEonGPU_BUILD_TESTS=ON
          -D HEonGPU_BUILD_EXAMPLES=ON
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++
          -B build"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/HEonGPU && cmake --build build"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/HEonGPU && cmake --install build"


Hecate build:
    extends:
        - .weekly_template
    stage: Hecate_build
    script:
        - echo "Hecate build"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/hecate-compiler && git log -n 1 HEAD"
        #- docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/hecate-compiler/script && ./Build.sh hecate"
        - >
          docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/hecate-compiler &&
          cmake -S . -B build -DMLIR_ROOT=${CI_INSTALL_DIR}/MLIR
          -DSEAL_ROOT=${CI_INSTALL_DIR}/SEAL
          -DHEonGPU_ROOT=${CI_INSTALL_DIR}/HEON
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++
          -DLLVM_EXTERNAL_LIT=${CI_DOCKER_HOME}/llvm-project/build/bin/llvm-lit"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/hecate-compiler && cmake --build build"
    artifacts:
        paths:
            - build/
        expire_in: 1 week

Setting Hecate python environment:
    extends:
        - .weekly_template
    stage: Hecate_env
    script:
        - echo "Hecate python environment"
        #- docker exec -i hecate_ci_container bash -c "cd hecate-compiler/script && ./Build.sh env"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME} && python3 -m venv .venv"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME} && source .venv/bin/activate && cd ${CI_DOCKER_HOME}/hecate-compiler && pip install -r requirements.txt"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME} && source .venv/bin/activate && 
            cd ${CI_DOCKER_HOME}/hecate-compiler/python/hecate && 
            python setup.py sdist --format=tar && 
            pip uninstall hecate --yes && pip install dist/hecate-0.0.1.tar"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME} && source .venv/bin/activate && 
            cd ${CI_DOCKER_HOME}/hecate-compiler/python/poly && 
            python setup.py sdist --format=tar && 
            pip uninstall poly --yes && 
            pip install dist/poly-0.0.1.tar"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME} && source .venv/bin/activate && 
            cd ${CI_DOCKER_HOME}/hecate-compiler/python/hetorch && 
            pip uninstall hetorch --yes || true && 
            pip install -e ."
    dependencies:
        - Hecate build
    artifacts:
        paths:
            - python/
        expire_in: 1 week


testing Pass of Hecate compiler:
    extends:
        - .weekly_template
    stage: testing_Hecate_Pass
    script:
        - echo "testing Pass of Hecate compiler"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME} && pwd && source .venv/bin/activate && cd ${CI_DOCKER_HOME}/hecate-compiler && cmake --build build --target check-hecate"
    dependencies:
        - Hecate build
        - Setting Hecate python environment
    allow_failure: true

# This script manually sets up test cases to display all benchmark results on GitLab website.
# For better maintainability, consider transitioning to an automated testing framework once the tests are reliable.
.benchmark_template:
    extends:
        - .weekly_template
    stage: testing_Hecate_Benchmark
    needs:
        - Hecate build
        - Setting Hecate python environment
    variables:
        COMPILER: "dacapo"
        WATERLINE: "40"
        LIBRARY: "SEAL"
        HARDWARE: "CPU"
    allow_failure: true

.benchmark_script:
  script:
    - echo "testing Hecate $CI_JOB_NAME Benchmark with waterscale $WATERLINE using $LIBRARY"
    - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME} && source .venv/bin/activate && 
        cd ${CI_DOCKER_HOME}/hecate-compiler &&
        source config.sh && 
        hc-trace $CI_JOB_NAME" || exit 1
    - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME} && source .venv/bin/activate && 
        cd ${CI_DOCKER_HOME}/hecate-compiler &&
        source config.sh && 
        export LLVM_SYMBOLIZER_PATH='${CI_INSTALL_DIR}/MLIR/bin/llvm-symbolizer' && 
        python3 ./examples/hc_opt.py $CI_JOB_NAME --opt $COMPILER --waterline $WATERLINE --library $LIBRARY --device $HARDWARE" || exit 1
    - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "set -e && 
        cd ${CI_DOCKER_HOME} &&
        source .venv/bin/activate && 
        cd ${CI_DOCKER_HOME}/hecate-compiler &&
        source config.sh && 
        echo 'y' | hc-test $CI_JOB_NAME --opt $COMPILER --waterline $WATERLINE --library $LIBRARY --device $HARDWARE > ${CI_RESULTS_DIR}/$CI_JOB_NAME-${WATERLINE}-${LIBRARY}-${COMPILER}-${HARDWARE}.txt" || exit 1
    - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "echo ${CI_RESULTS_DIR}/$CI_JOB_NAME-${WATERLINE}-${LIBRARY}-${COMPILER}-${HARDWARE}.txt" || exit 1
  after_script:
    - date
    - echo "Cleaning up benchmark processes"
    - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "
        pkill -f python3 || echo 'No python3 process found';
        pkill -f hecate-opt || echo 'No hecate-opt process found';
        " || true
Initialization:
    extends:
        - .benchmark_template
    script:
        - echo "Preparing and Initialization"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "rm ${CI_RESULTS_DIR}/*.txt"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "cd ${CI_DOCKER_HOME}/script/ && ./Model_Download.sh"
    needs:
        - Hecate build
        - Setting Hecate python environment
    artifacts:
        paths:
            - examples/data/
        expire_in: 1 week


# HEONGPU-eva
HarrisCornerDetection-40-HEONGPU-eva :
    extends:
        - .benchmark_template
        - .benchmark_script
    variables:
        CI_JOB_NAME: "HarrisCornerDetection"
        LIBRARY: "HEONGPU"
        HARDWARE: "GPU"
        COMPILER: "eva"
    needs:
        - Initialization
        - Hecate build
        - Setting Hecate python environment

SobelFilter-40-HEONGPU-eva :
    extends:
        - .benchmark_template
        - .benchmark_script
    variables:
        CI_JOB_NAME: "SobelFilter"
        LIBRARY: "HEONGPU"
        HARDWARE: "GPU"
        COMPILER: "eva"
    # For Sequential Testing
    needs:
        - Initialization
        - HarrisCornerDetection-40-HEONGPU-eva
        - Hecate build
        - Setting Hecate python environment

LinearRegression-40-HEONGPU-eva :
    extends:
        - .benchmark_template
        - .benchmark_script
    variables:
        CI_JOB_NAME: "LinearRegression"
        LIBRARY: "HEONGPU"
        HARDWARE: "GPU"
        COMPILER: "eva"
    needs:
        - Initialization
        - SobelFilter-40-HEONGPU-eva
        - Hecate build
        - Setting Hecate python environment

PolynomialRegression-40-HEONGPU-eva :
    extends:
        - .benchmark_template
        - .benchmark_script
    variables:
        CI_JOB_NAME: "PolynomialRegression"
        LIBRARY: "HEONGPU"
        HARDWARE: "GPU"
        COMPILER: "eva"
    needs:
        - Initialization
        - LinearRegression-40-HEONGPU-eva
        - Hecate build
        - Setting Hecate python environment

Multivariate-40-HEONGPU-eva :
    extends:
        - .benchmark_template
        - .benchmark_script
    variables:
        CI_JOB_NAME: "Multivariate"
        LIBRARY: "HEONGPU"
        HARDWARE: "GPU"
        COMPILER: "eva"
    needs:
        - Initialization
        - PolynomialRegression-40-HEONGPU-eva
        - Hecate build
        - Setting Hecate python environment

# HEaaN - Dacapo
ResNet-40-HEONGPU-Dacapo :
    extends:
        - .benchmark_template
        - .benchmark_script
    variables:
        CI_JOB_NAME: "ResNet_mpcb"
        LIBRARY: "HEONGPU"
        HARDWARE: "GPU"
    # For Sequential Testing
    needs:
        - Initialization
        - Multivariate-40-HEONGPU-eva
        - Hecate build
        - Setting Hecate python environment

AlexNet-40-HEONGPU-Dacapo :
    extends:
        - .benchmark_template
        - .benchmark_script
    variables:
        CI_JOB_NAME: "AlexNet_mpcb"
        LIBRARY: "HEONGPU"
        HARDWARE: "GPU"
    # For Sequential Testing
    needs:
        - Initialization
        - ResNet-40-HEONGPU-Dacapo
        - Hecate build
        - Setting Hecate python environment

VGG16-40-HEONGPU-Dacapo :
    extends:
        - .benchmark_template
        - .benchmark_script
    variables:
        CI_JOB_NAME: "VGG16_mpcb"
        LIBRARY: "HEONGPU"
        HARDWARE: "GPU"
    # For Sequential Testing
    needs:
        - Initialization
        - AlexNet-40-HEONGPU-Dacapo
        - Hecate build
        - Setting Hecate python environment

SqueezeNet-40-HEONGPU-Dacapo :
    extends:
        - .benchmark_template
        - .benchmark_script
    variables:
        CI_JOB_NAME: "SqueezeNet_mpcb"
        LIBRARY: "HEONGPU"
        HARDWARE: "GPU"
    # For Sequential Testing
    needs:
        - Initialization
        - VGG16-40-HEONGPU-Dacapo
        - Hecate build
        - Setting Hecate python environment

MobileNet-40-HEONGPU-Dacapo :
    extends:
        - .benchmark_template
        - .benchmark_script
    variables:
        CI_JOB_NAME: "MobileNet_mpcb"
        LIBRARY: "HEONGPU"
        HARDWARE: "GPU"
    # For Sequential Testing
    needs:
        - Initialization
        - SqueezeNet-40-HEONGPU-Dacapo
        - Hecate build
        - Setting Hecate python environment

# Using tools, show all results of testing to a file.
save_result:
    stage: save_result
    script:
        - echo "Save Results"
        - docker exec -i -u ${CI_USER} hecate_ci_container bash -c "python3 ${CI_DOCKER_HOME}/hecate-compiler/script/ci_result.py ${CI_RESULTS_DIR}"
    tags:
        - hestia_runner
    dependencies:
        - Hecate build
    rules:
        - if: "$CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE == 'schedule' && ($SCHEDULE_TYPE == 'weekly' || $SCHEDULE_TYPE == 'irregularly')"
          when: always


